jenkins_server:
  - image: jenkins/build-jenkins
  - ports: "8080:8080"
  - ports: "50000:50000"
  - ports: "2222:22"

jenkins_swarm_client:
  - image: jenkins/build-jenkins_slave
  - ports: "8081:8080"
  - ports: "2223:22"